# Generated by Django 5.2.17 on 2026-09-14 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('public_id', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('concept', '概念卡'), ('unit', '教程单元'), ('compare', '对照'), ('pitfall', '坑'), ('project', '项目课'), ('case', '案例'), ('news', '快讯'), ('issue', '期刊'), ('entity', '实体'), ('glossary', '术语'), ('asset', '资源'), ('lab', '实验'), ('quiz', '测验')], max_length=20)),
                ('level', models.CharField(default='L1', max_length=4)),
                ('domain', models.CharField(default='general', max_length=20)),
                ('track', models.SlugField(blank=True)),
                ('unit_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=200)),
                ('body_md', models.TextField()),
                ('html', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('idea', '选题'), ('assigned', '已派'), ('researching', '调研'), ('drafting', '起草'), ('machine_qa', '机审'), ('factcheck', '事实清单'), ('editing', '编辑'), ('legal', '法务'), ('scheduled', '排期'), ('published', '已发布'), ('needs_update', '待更新'), ('archived', '作废')], default='drafting', max_length=20)),
                ('access', models.CharField(choices=[('free', '免费'), ('supporter', '支持者'), ('code', '内容码'), ('group', '分组')], default='free', max_length=20)),
                ('group_slug', models.SlugField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
                ('node_ids', models.JSONField(default=list)),
                ('prereqs', models.JSONField(default=list)),
                ('next_nodes', models.JSONField(default=list)),
                ('ai', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('review_by', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('changelog', models.JSONField(default=list)),
                ('generation_log', models.JSONField(blank=True, null=True)),
                ('qa_report', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=80)),
                ('body_md', models.TextField()),
                ('html', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('body_md', models.TextField()),
                ('editor_id', models.BigIntegerField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.contentnode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Erratum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errata', to='content.contentnode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='content.contentnode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('term', models.CharField(max_length=40, unique=True)),
                ('definition', models.CharField(max_length=60)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.contentnode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
