# Generated by Django 5.2.17 on 2026-09-14 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('q', models.CharField(max_length=100)),
                ('zero', models.BooleanField(default=False)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('signal', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=80)),
                ('suggested_kind', models.CharField(default='concept', max_length=20)),
                ('suggested_level', models.CharField(default='L1', max_length=4)),
                ('score', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(default='open', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
