# Generated by Django 5.2.17 on 2026-09-14 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('src', models.CharField(max_length=200, unique=True)),
                ('dst', models.CharField(max_length=200)),
                ('code', models.PositiveSmallIntegerField(default=301)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
