# Generated by Django 5.2.17 on 2026-09-14 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=80)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('body_md', models.TextField(blank=True)),
                ('html', models.TextField(blank=True)),
                ('status', models.CharField(default='published', max_length=20)),
                ('items', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('tier', models.CharField(default='official', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
