# Generated by Django 5.2.17 on 2026-09-14 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(default='tool', max_length=20)),
                ('official_url', models.URLField()),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('claimed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
