from django.urls import path

from content import views

urlpatterns = [
    path("", views.home, name="home"),
    path("articles/<slug:slug>", views.article, name="article"),
    path("articles/<slug:slug>/feedback", views.feedback, name="feedback"),
    path("articles/<slug:slug>/bookmark", views.bookmark, name="bookmark"),
    path("articles/<slug:slug>/highlight", views.highlight, name="highlight"),
    path("articles/<slug:slug>/report", views.report_error, name="report_error"),
    path("learn", views.learn, name="learn"),
    path("learn/<slug:slug>", views.track, name="track"),
    path("learn/<slug:track>/<slug:unit>", views.unit, name="unit"),
    path("glossary", views.glossary, name="glossary"),
    path("glossary/<str:term>", views.glossary_term, name="glossary_term"),
    path("compare", views.compare_list, name="compare_list"),
    path("compare/<slug:slug>", views.compare, name="compare"),
    path("projects", views.projects, name="projects"),
    path("topics", views.topics_index, name="topics_index"),
    path("topics/<slug:slug>", views.topic, name="topic"),
    path("tools", views.tools, name="tools"),
    path("tools/<slug:slug>/claim", views.claim_tool, name="claim_tool"),
    path("entities/<slug:slug>", views.entity_page, name="entity"),
    path("models", views.entity_list, {"kind": "model"}, name="models"),
    path("companies", views.entity_list, {"kind": "company"}, name="companies"),
    path("papers", views.entity_list, {"kind": "paper"}, name="papers"),
    path("authors", views.authors, name="authors"),
    path("authors/<int:pk>", views.author, name="author"),
    path("about", views.static_page, {"slug": "about"}, name="about"),
    path("disclosure", views.static_page, {"slug": "disclosure"}, name="disclosure"),
    path("ads-policy", views.static_page, {"slug": "ads-policy"}, name="ads_policy"),
    path("license", views.static_page, {"slug": "license"}, name="license"),
    path("privacy", views.static_page, {"slug": "privacy"}, name="privacy"),
    path("errata", views.errata_list, name="errata"),
    path("changelog", views.static_page, {"slug": "changelog"}, name="changelog"),
    path("pricing", views.pricing, name="pricing"),
    path("join", views.join, name="join"),
]
