# Generated by Django 5.2.17 on 2026-09-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='last4',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
