# Generated by Django 5.2.17 on 2026-09-14 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('node_id', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('level', models.CharField(choices=[('L0', 'L0'), ('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('L5', 'L5'), ('L6', 'L6'), ('L7', 'L7')], max_length=4)),
                ('domain', models.CharField(choices=[('general', '通用认知'), ('office', '办公与学习'), ('dev-agent', '开发与 Agent'), ('aigc', 'AIGC 创作'), ('industry', '行业与岗位'), ('theory', '原理与研究')], max_length=20)),
                ('status', models.CharField(default='empty', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=80)),
                ('summary', models.CharField(max_length=200)),
                ('level_from', models.CharField(default='L0', max_length=4)),
                ('level_to', models.CharField(default='L7', max_length=4)),
                ('domain', models.CharField(default='dev-agent', max_length=20)),
                ('status', models.CharField(default='published', max_length=20)),
                ('eta_hours', models.PositiveIntegerField(default=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(default='prereq', max_length=20)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='graph.graphnode')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='graph.graphnode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('src', 'dst', 'kind'), name='uniq_edge')],
            },
        ),
        migrations.CreateModel(
            name='PathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('unit_index', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=80)),
                ('goal', models.CharField(max_length=200)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.contentnode')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='graph.learningpath')),
            ],
            options={
                'ordering': ['unit_index'],
                'constraints': [models.UniqueConstraint(fields=('path', 'unit_index'), name='uniq_path_item')],
            },
        ),
    ]
