# Generated by Django 5.2.17 on 2026-09-14 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=80)),
                ('obj_type', models.CharField(max_length=80)),
                ('obj_id', models.CharField(blank=True, max_length=80)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.JSONField()),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notice', models.CharField(blank=True, max_length=80)),
                ('maintenance', models.BooleanField(default=False)),
                ('maintenance_until', models.DateTimeField(blank=True, null=True)),
                ('card_shop_url', models.URLField(blank=True)),
                ('flags_version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_type', models.CharField(max_length=80)),
                ('obj_id', models.CharField(max_length=80)),
                ('from_state', models.CharField(max_length=40)),
                ('to_state', models.CharField(max_length=40)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(max_length=200)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
