# Generated by Django 5.2.17 on 2026-09-14 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=80)),
                ('kind', models.CharField(default='concept', max_length=20)),
                ('level', models.CharField(default='L1', max_length=4)),
                ('domain', models.CharField(default='general', max_length=20)),
                ('angle', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='open', max_length=20)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.contentnode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.CharField(max_length=240)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='content.contentnode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(default='writer', max_length=20)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('model', models.CharField(blank=True, max_length=40)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_cents', models.PositiveIntegerField(default=0)),
                ('log', models.JSONField(blank=True, default=dict)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generation.brief')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=40)),
                ('version', models.CharField(max_length=20)),
                ('body', models.TextField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_prompt_ver')],
            },
        ),
        migrations.CreateModel(
            name='QaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('gates', models.JSONField(default=dict)),
                ('passed', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_reports', to='content.contentnode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
